name: CI
on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
  workflow_dispatch:

env:
  DEPLOYMENT_TARGET: "14.0"

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Select Xcode 26.2
        run: sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
      - run: xcodebuild -version
      - name: Build
        run: |
          xcodebuild -project Thaw.xcodeproj \
            -scheme Thaw \
            -destination 'platform=macOS' \
            -configuration Release \
            MACOSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }} \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
