name: CI
on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - "Package.swift"
      - "**/*.swift"
  workflow_dispatch:

env:
  DEPLOYMENT_TARGET: "14.0"

jobs:
  lint:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v5
        with:
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /usr/local/Frameworks
          # Maybe replace with brewfile
          key: ${{ runner.os }}-brew-${{ hashFiles('.github/workflows/ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-brew-
      - name: Install SwiftLint
        run: brew update && brew install swiftlint || brew upgrade swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict

  build:
    if: github.event.pull_request.draft == false
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: |
          xcodebuild -project Thaw.xcodeproj \
            -scheme Thaw \
            -destination 'platform=macOS' \
            -configuration Release \
            MACOSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }} \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            build
